// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "Timed_cvMat.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
RTC::cvMat::operator>>= (cdrStream &_n) const
{
  _n.marshalString(data_type,0);
  mat_type >>= _n;
  width >>= _n;
  height >>= _n;
  bpp >>= _n;
  _n.marshalBoolean(is_shared);
  _n.marshalString(name,0);
  memory_index >>= _n;
  length >>= _n;
  (const _CORBA_Unbounded_Sequence_Octet&) data >>= _n;

}

void
RTC::cvMat::operator<<= (cdrStream &_n)
{
  data_type = _n.unmarshalString(0);
  (::CORBA::Long&)mat_type <<= _n;
  (::CORBA::UShort&)width <<= _n;
  (::CORBA::UShort&)height <<= _n;
  (::CORBA::UShort&)bpp <<= _n;
  is_shared = _n.unmarshalBoolean();
  name = _n.unmarshalString(0);
  (::CORBA::Long&)memory_index <<= _n;
  (::CORBA::Long&)length <<= _n;
  (_CORBA_Unbounded_Sequence_Octet&)data <<= _n;

}

void
RTC::Timed_cvMat::operator>>= (cdrStream &_n) const
{
  (const Time&) tm >>= _n;
  (const cvMat&) data >>= _n;

}

void
RTC::Timed_cvMat::operator<<= (cdrStream &_n)
{
  (Time&)tm <<= _n;
  (cvMat&)data <<= _n;

}

