// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __VisionDataType_hh__
#define __VisionDataType_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_VisionDataType
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_VisionDataType
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_VisionDataType
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE Vision

_CORBA_MODULE_BEG

  struct Time {
    typedef _CORBA_ConstrType_Fix_Var<Time> _var_type;

    
    ::CORBA::ULong sec;

    ::CORBA::ULong msec;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef Time::_var_type Time_var;

  typedef Time& Time_out;

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_Time;

  struct ReceptiveField {
    typedef _CORBA_ConstrType_Variable_Var<ReceptiveField> _var_type;

    
    Time tm;

    ::CORBA::UShort x;

    ::CORBA::UShort y;

    ::CORBA::UShort t;

    ::CORBA::UShort type;

    typedef _CORBA_Unbounded_Sequence_Octet _pixels_seq;
    _pixels_seq pixels;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef ReceptiveField::_var_type ReceptiveField_var;

  typedef _CORBA_ConstrType_Variable_OUT_arg< ReceptiveField,ReceptiveField_var > ReceptiveField_out;

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_ReceptiveField;

  struct Image {
    typedef _CORBA_ConstrType_Variable_Var<Image> _var_type;

    
    Time tm;

    ::CORBA::ULong x;

    ::CORBA::ULong y;

    ::CORBA::ULong t;

    ::CORBA::ULong type;

    typedef _CORBA_Unbounded_Sequence_Octet _pixels_seq;
    _pixels_seq pixels;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef Image::_var_type Image_var;

  typedef _CORBA_ConstrType_Variable_OUT_arg< Image,Image_var > Image_out;

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_Image;

_CORBA_MODULE_END



_CORBA_MODULE POA_Vision
_CORBA_MODULE_BEG

_CORBA_MODULE_END



_CORBA_MODULE OBV_Vision
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

extern void operator<<=(::CORBA::Any& _a, const Vision::Time& _s);
extern void operator<<=(::CORBA::Any& _a, Vision::Time* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, Vision::Time*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const Vision::Time*& _sp);

extern void operator<<=(::CORBA::Any& _a, const Vision::ReceptiveField& _s);
extern void operator<<=(::CORBA::Any& _a, Vision::ReceptiveField* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, Vision::ReceptiveField*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const Vision::ReceptiveField*& _sp);

extern void operator<<=(::CORBA::Any& _a, const Vision::Image& _s);
extern void operator<<=(::CORBA::Any& _a, Vision::Image* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, Vision::Image*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const Vision::Image*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_VisionDataType
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_VisionDataType
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_VisionDataType
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_VisionDataType
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_VisionDataType
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_VisionDataType
#endif

#endif  // __VisionDataType_hh__

